// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    localEquipmentNodes,
    localEquipmentUsageLogs,
    localReadings,
    localAlerts,
    localReports,
    localCustomerUtilityEntries,
    localAccountProfiles,
    localSyncMetadata,
  ];
  late final Shape0 localEquipmentNodes = Shape0(
      source: i0.VersionedTable(
        entityName: 'local_equipment_nodes',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(node_id)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 localEquipmentUsageLogs = Shape1(
      source: i0.VersionedTable(
        entityName: 'local_equipment_usage_logs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(log_id)',
        ],
        columns: [
          _column_4,
          _column_0,
          _column_5,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 localReadings = Shape2(
      source: i0.VersionedTable(
        entityName: 'local_readings',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(remote_id)',
        ],
        columns: [
          _column_6,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 localAlerts = Shape3(
      source: i0.VersionedTable(
        entityName: 'local_alerts',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(remote_id)',
        ],
        columns: [
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 localReports = Shape4(
      source: i0.VersionedTable(
        entityName: 'local_reports',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(remote_id)',
        ],
        columns: [
          _column_6,
          _column_8,
          _column_10,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 localCustomerUtilityEntries = Shape5(
      source: i0.VersionedTable(
        entityName: 'local_customer_utility_entries',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(remote_id, user_id)',
        ],
        columns: [
          _column_6,
          _column_11,
          _column_12,
          _column_13,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 localAccountProfiles = Shape6(
      source: i0.VersionedTable(
        entityName: 'local_account_profiles',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(user_id)',
        ],
        columns: [
          _column_11,
          _column_14,
          _column_15,
          _column_16,
          _column_7,
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 localSyncMetadata = Shape7(
      source: i0.VersionedTable(
        entityName: 'local_sync_metadata',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(scope)',
        ],
        columns: [
          _column_18,
          _column_19,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get nodeId =>
      columnsByName['node_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get facilityName =>
      columnsByName['facility_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nodeName =>
      columnsByName['node_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('node_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('facility_name', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('node_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('payload', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get nodeId =>
      columnsByName['node_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get loggedAt =>
      columnsByName['logged_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('log_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>('logged_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get remoteId =>
      columnsByName['remote_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>('remote_id', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get remoteId =>
      columnsByName['remote_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDeleted =>
      columnsByName['is_deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get detectedAt =>
      columnsByName['detected_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('status', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('is_deleted', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_deleted IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('detected_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get remoteId =>
      columnsByName['remote_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isDeleted =>
      columnsByName['is_deleted']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get remoteId =>
      columnsByName['remote_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get utility =>
      columnsByName['utility']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get periodMonth =>
      columnsByName['period_month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('user_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('utility', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('period_month', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fullName =>
      columnsByName['full_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get verifiedAt =>
      columnsByName['verified_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('full_name', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('role', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>('verified_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>('scope', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('synced_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
    ));
