insert into public.alerts (
  alert_type, state, detected_at, signature, severity, explanation, status,
  is_deleted, produced_mld, billed_mld, loss_mld, loss_pct, data_year,
  source_scope, utility_type, source_key
) values
  ('electricity_hotspot', 'Perak', now(), 'Electricity loss hotspot', 'low',
   'Perak shows 11.6% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 7017.8694, 6202.7321, 815.1373, 11.6152, 2024,
   'state', 'electricity', 'state:electricity:Perak:2024'),
  ('electricity_hotspot', 'Kelantan', now(), 'Electricity loss hotspot', 'low',
   'Kelantan shows 11.3% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 7275.8698, 6453.0146, 822.8552, 11.3094, 2024,
   'state', 'electricity', 'state:electricity:Kelantan:2024'),
  ('electricity_hotspot', 'Terengganu', now(), 'Electricity loss hotspot', 'low',
   'Terengganu shows 7.3% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 6839.6570, 6342.8791, 496.7779, 7.2632, 2024,
   'state', 'electricity', 'state:electricity:Terengganu:2024'),
  ('electricity_hotspot', 'Kedah', now(), 'Electricity loss hotspot', 'low',
   'Kedah shows 6.6% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 7140.2507, 6668.0867, 472.1640, 6.6127, 2024,
   'state', 'electricity', 'state:electricity:Kedah:2024'),
  ('electricity_hotspot', 'Sabah', now(), 'Electricity loss hotspot', 'low',
   'Sabah shows 3.8% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 6523.6306, 6273.3301, 250.3006, 3.8368, 2024,
   'state', 'electricity', 'state:electricity:Sabah:2024'),
  ('electricity_hotspot', 'Johor', now(), 'Electricity loss hotspot', 'low',
   'Johor shows 2.4% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 7058.9546, 6889.7300, 169.2246, 2.3973, 2024,
   'state', 'electricity', 'state:electricity:Johor:2024'),
  ('electricity_hotspot', 'Perlis', now(), 'Electricity loss hotspot', 'low',
   'Perlis shows -0.3% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 6541.0900, 6562.0739, -20.9839, -0.3208, 2024,
   'state', 'electricity', 'state:electricity:Perlis:2024'),
  ('electricity_hotspot', 'Melaka', now(), 'Electricity loss hotspot', 'low',
   'Melaka shows -1.0% of supplied electricity unaccounted for in 2024, above the national average of -1.4%. A gap this large between supply and metered consumption points to distribution losses or meter tampering. Recommend a field audit of the distribution grid.',
   'pending_review', false, 6614.2941, 6677.1530, -62.8588, -0.9503, 2024,
   'state', 'electricity', 'state:electricity:Melaka:2024'),
  ('electricity_tampering', 'Malaysia', now(), 'Potential tampering', 'low',
   'National electricity losses spiked to 2.9% of supply (1617 kWh) in this period of 2018 — a statistically abnormal jump (z-score above the tampering threshold) versus the surrounding months. Consistent with large-scale meter tampering or an unmetered draw. Recommend a grid-level investigation.',
   'pending_review', false, 55033.5083, 13224.6169, 1616.7010, 2.9377, 2018,
   'state', 'electricity', 'tampering:2018-3'),
  ('electricity_tampering', 'Malaysia', now(), 'Potential tampering', 'low',
   'National electricity losses spiked to 1.7% of supply (889 kWh) in this period of 2022 — a statistically abnormal jump (z-score above the tampering threshold) versus the surrounding months. Consistent with large-scale meter tampering or an unmetered draw. Recommend a grid-level investigation.',
   'pending_review', false, 52106.5482, 12896.3879, 889.0147, 1.7061, 2022,
   'state', 'electricity', 'tampering:2022-2'),
  ('electricity_tampering', 'Malaysia', now(), 'Potential tampering', 'low',
   'National electricity losses spiked to 1.4% of supply (710 kWh) in this period of 2023 — a statistically abnormal jump (z-score above the tampering threshold) versus the surrounding months. Consistent with large-scale meter tampering or an unmetered draw. Recommend a grid-level investigation.',
   'pending_review', false, 51884.1544, 13056.1507, 710.1693, 1.3688, 2023,
   'state', 'electricity', 'tampering:2023-2'),
  ('electricity_tampering', 'Malaysia', now(), 'Potential tampering', 'low',
   'National electricity losses spiked to 1.2% of supply (719 kWh) in this period of 2024 — a statistically abnormal jump (z-score above the tampering threshold) versus the surrounding months. Consistent with large-scale meter tampering or an unmetered draw. Recommend a grid-level investigation.',
   'pending_review', false, 58262.4963, 14753.4967, 719.3474, 1.2347, 2024,
   'state', 'electricity', 'tampering:2024-2'),
  ('nrw_hotspot', 'Perlis', now(), 'NRW hotspot', 'high',
   'Perlis loses 59.7% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 243.0000, 98.0000, 145.0000, 59.6708, 2022,
   'state', 'water', 'state:water:Perlis:2022'),
  ('nrw_hotspot', 'Sabah', now(), 'NRW hotspot', 'high',
   'Sabah loses 55.0% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 1404.0000, 632.0000, 772.0000, 54.9858, 2022,
   'state', 'water', 'state:water:Sabah:2022'),
  ('nrw_hotspot', 'Kelantan', now(), 'NRW hotspot', 'high',
   'Kelantan loses 53.8% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 517.0000, 239.0000, 278.0000, 53.7718, 2022,
   'state', 'water', 'state:water:Kelantan:2022'),
  ('nrw_hotspot', 'Kedah', now(), 'NRW hotspot', 'high',
   'Kedah loses 51.3% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 1597.0000, 777.0000, 820.0000, 51.3463, 2022,
   'state', 'water', 'state:water:Kedah:2022'),
  ('nrw_hotspot', 'Pahang', now(), 'NRW hotspot', 'high',
   'Pahang loses 50.0% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 1337.0000, 668.0000, 669.0000, 50.0374, 2022,
   'state', 'water', 'state:water:Pahang:2022'),
  ('nrw_hotspot', 'Sarawak', now(), 'NRW hotspot', 'medium',
   'Sarawak loses 43.4% of treated water in 2022, above the national average of 37.4%. A loss this high points to distribution-network leakage rather than metering error. Recommend a field inspection of the district network.',
   'pending_review', false, 1881.0000, 1065.0000, 816.0000, 43.3812, 2022,
   'state', 'water', 'state:water:Sarawak:2022')
on conflict (source_key) do nothing;
